// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace test.Models;

public partial class AppDbContext : DbContext
{
    private readonly string _dbPath;
    public AppDbContext(string dbPath)
    {
        _dbPath = dbPath;
    }

    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Record> Record { get; set; }



    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlite($"Data Source={_dbPath}");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Record>(entity =>
        {
            entity.Property(e => e.Device).IsRequired();
            entity.Property(e => e.MaterialRequestNumber).IsRequired();
            entity.Property(e => e.Person).IsRequired();
            entity.Property(e => e.RepairRequestNumber).IsRequired();
            entity.Property(e => e.Stock)
                .HasColumnName("Stock");
            entity.Property(e => e.Timestamp).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}