// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace test.Models;

public partial class Record
{
    public long RecordId { get; set; }
    [DisplayName("時間")]
    public string Timestamp { get; set; }
    [DisplayName("姓名")]
    public string Person { get; set; }
    [DisplayName("領料單號")]
    public string MaterialRequestNumber { get; set; }
    [DisplayName("報修單號")]
    public string RepairRequestNumber { get; set; }
    [DisplayName("領用設備")]
    public string Device { get; set; }
    [DisplayName("備註")]
    public string Remarks { get; set; }
    public long Stock { get; set; }
}