// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace test2.Models;

public partial class ChildCategory
{
    public long ChildCategoryId { get; set; }

    public long CategoryId { get; set; }

    public string ChildCategoryName { get; set; }

    public virtual Category Category { get; set; }
}