// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace tt0103.Models;

public partial class ESQtempdatabasedbContext : DbContext
{
    public ESQtempdatabasedbContext(DbContextOptions<ESQtempdatabasedbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<ChildCategory> ChildCategories { get; set; }

    public virtual DbSet<Record> Records { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.ToTable("Category");

            entity.Property(e => e.CategoryName).IsRequired();
        });

        modelBuilder.Entity<ChildCategory>(entity =>
        {
            entity.ToTable("ChildCategory");

            entity.Property(e => e.ChildCategoryName).IsRequired();

            entity.HasOne(d => d.Category).WithMany(p => p.ChildCategories)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Record>(entity =>
        {
            entity.ToTable("Record");

            entity.Property(e => e.DeliveryDate).IsRequired();
            entity.Property(e => e.MaterialNo).IsRequired();
            entity.Property(e => e.Model).IsRequired();
            entity.Property(e => e.Price)
                .IsRequired()
                .HasColumnType("NUMERIC");
            entity.Property(e => e.Quantity).IsRequired();
            entity.Property(e => e.Vendor).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}